# travis
sudo: false
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      after_success:
      # this prevents the tests to upload stuff to coveralls.io
        - echo "done"

    - python: 3.6
      #taken from https://quick-sphinx-tutorial.readthedocs.io/en/latest/advanced.html
      branches:
        only:
          - master

      env: tests-doc-creation
      sudo: false
      install:
        - python -m pip install -U -r requirements_dev.txt
        - python setup.py install
      script:
        - cd docs; make clean_all api_docs html linkcheck
      after_success:
        # this prevents the tests to upload stuff to coveralls.io
        - echo "done"

    # LINUX
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7-dev"  # 3.7 development branch
      env: TOXENV=py37

    # OSX
    - language: generic
      python: 3.6
      env: osx-py36
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - python -m pip install -U pip>=8.1.2
        - pip install tox coveralls
        - pip uninstall -y virtualenv
        - conda install -y --name py36 virtualenv
        - pip freeze
      script: tox -e py36

#    - language: generic
#      python: 3.7
#      env: osx-py37
#      os: osx
#      before_install:
#        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
#        - bash miniconda.sh -b -p $HOME/miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - conda update conda -y
#        - conda create -n py37 python=3.7 -y
#      install:
#        - source activate py37
#        - python -m pip install -U pip>=8.1.2
#        - pip install tox coveralls
#        - pip uninstall -y virtualenv
#        - conda install -y --name py37 virtualenv
#        - pip freeze
#      script: tox -e py37

    - python: 3.6
      env: win_coverage
      install:
        - pip install git+https://github.com/Robpol86/appveyor-artifacts.git coveralls
      script:
        - appveyor-artifacts -m download
      after_success:
        - coveralls
        - coverage erase

install:
  - python -m pip install -U pip>=8.1.2
  - pip install tox coveralls

script: tox

after_success:
    - coveralls
    - coverage erase
