# travis
sudo: false
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=flake8
      before_install:
        - echo "before_install"
        - python -m pip install -U pip>=9.0.1
        - pip install tox
      script:
        - tox
      after_success:
      # this prevents the tests to upload stuff to coveralls.io
        - echo "done"

    - python: 3.6
      # taken from https://quick-sphinx-tutorial.readthedocs.io/en/latest/advanced.html
      env: TOXENV=docs
      before_install:
        - echo "before_install"
        - python -m pip install -U pip>=9.0.1
        - pip install tox
      script:
        - tox
      after_success:
        # this prevents the tests to upload stuff to coveralls.io
        - echo "done"

    # LINUX
    - python: "3.6"
      env: linux-py36

    - python: "3.7-dev"  # 3.7 development branch
      env: linux-py37

    # OSX
    - language: generic
      python: 3.6
      os: osx
      env:
        - osx-py36
      before_install:
        - echo "before_install"
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
        - source activate py36
        - python -m pip install -U pip>=9.0.1

    - language: generic
      python: 3.7
      env: osx-py37
      os: osx
      before_install:
        - echo "before_install"
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
        - source activate py37
        - python -m pip install -U pip>=9.0.1

#    - python: 3.6
#      env: win_coverage
#      install:
#        - pip install git+https://github.com/Robpol86/appveyor-artifacts.git coveralls
#      script:
#        - appveyor-artifacts -m download
#      after_success:
#        - coveralls
#        - coverage erase

before_install:
  - echo "before_install"
  - python -m pip install -U pip>=9.0.1

install:
  - pip install coveralls
  - pip install -r requirements_dev.txt

script:
  - pip install .
  - py.test --cov=lmfit_varpro --cov-config .coveragerc tests/
  - pip freeze

after_success:
  - coveralls
  - coverage erase

notifications:
  slack:
    rooms:
      - secure: "VidmiSSh3NBpBRsbe/Y4z02rEW/VNvW6IA47AgbVQkWM2D/f5p26vqequ4GHCDNJJzSUn5FX85eTj+p9nssXeVWJW3/KNp/NX0DTiylixj1Ep4myTfhWJwQlV56bq+7OZCjwRF290oTz4XECUQ6cL/+JeYH3E4GaAz3T9kxhpfZfP+dMJ8FIjQgaT5UorlcY3uFjx4FgScTyJPNyv0vzwpNc2KQVIWBVe3KBpnqkoYDGCjU4rVUa61HJ+agfYi0UelxyaRZKyMw1+EjTPZqpLBX2QKreAv7wWvbsVvmb+3jC/jlndVSN0HSG513nSUEAmd10I2YoWSPj5Ri8aMcBkJLVbt/Y8pedoHcAY8yam/Z5Pqh4lqvaP9tGJTLoIFzFkmrWnvtnx4bp+8QKSvK9SFhX2l90AoNKhwpYnAssMKgbtCeR3IJCEU99XpsT2DiKknvJKLQ+dcATv05b7XEnu5be46LllcykfoF6L64ZUyBPimlleGufdWNJzs/VWVHbVxZePlVpfX/Bp9sCq/uX1u3xosA1NWjiexw1R37u/fBTxELFuRR/jYOm7ON/YC/2yjHox05009WZy0IIzxwURpBH6YU0mQgXYFgTJGkNLN3418pXr0doN2LNgrfBUbAcD8jFVyx7aOJiGee3TP7/MKZRLhJcWs4uUKNWCqgtPbs="